# Generated by Django 3.2 on 2022-08-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('aka', models.TextField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=10, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('api_key', models.CharField(blank=True, max_length=10, unique=True)),
                ('authors', models.ManyToManyField(blank=True, to='req_app.Author')),
            ],
        ),
    ]
